import { Roboto } from 'next/font/google'
import Components from '@/components'
import './globals.css'


const roboto = Roboto({ subsets: ['latin'],weight: "500"})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ `${ roboto.className } max-w-[100vw] overflow-x-hidden` }>
        <Components children={ children } />
      </body>
    </html>
  )
}
