import { Inter } from 'next/font/google'
import './globals.css'
import Components from '@/components'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ inter.className + "max-w-[100vw] overflow-x-hidden" }>
        <Components children={ children } />
      </body>
    </html>
  )
}
